[package]
name = "rapier_snippets_rust3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier3d = "0.19.0"
nalgebra = { version = "0.32.5", features = ["convert-glam025"] }
glam = "0.25.0"
