name: Rapier CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-code-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Code snippets compilation check + tests
        run: cd docs-examples && cargo test
  check-injection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check injection script
        run: find docs/user_guides/templates/ -type f -print0 | OUTPUT_FOLDER=docs/user_guides/templates_injected xargs -0 ./inject_code_in_user_guides.sh
