name: Rapier CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-code-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Code snippets compilation check + tests
        run: cd docs-examples && cargo test
  check-injection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install --force -g node@16 && yarn
      - name: Check template generation
        run: ./generate_user_guides.sh && PUBLISH_MODE=1 yarn build
