name: Rapier CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-code-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Code snippets compilation check
        run: cd docs-examples && cargo check
